# Site settings
# title: Your awesome title
# username: yourname
# email: your-email@domain.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "/"
# url: "http://yourdomain.com"
# aboutme: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
# ads: /images/ads.jpg

# Build settings
markdown: kramdown# Site settings
title: ROHIT CHOUHAN
username: rchouhan
email: rohit170590@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, ROHIT CHOUHAN here.
baseurl: "/"
url: "https://rchouhan170590.github.io/rohit.chouhan.github.io/"
aboutme: >
 "I'm a Rohit Chouhan. I am self-motivated and hardworking with broad skills. 
 A key strength is a communication, building strong relationships with people 
 in order to deliver the best results.​"
ads: /images/rohit.jpeg

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
paginate_path: "/page:num/"

# Comment thread setting
disqus_forumname: tranquil-theme

gems: [jekyll-paginate]
paginate: 3
paginate_path: "/page:num/"

# Comment thread setting
disqus_forumname: tranquil-theme