# Site settings
title: ROHIT CHOUHAN
username: rchouhan
email: rohit170590@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, ROHIT CHOUHAN here.
baseurl: "/"
url: "https://rchouhan170590.github.io/rohit.chouhan.github.io/"
aboutme: >
 "I'm a Rohit Chouhan. I am self-motivated and hardworking with broad skills. 
 A key strength is a communication, building strong relationships with people 
 in order to deliver the best results.​"
ads: /images/rohit.jpeg

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
paginate_path: "/page:num/"

# Comment thread setting
disqus_forumname: tranquil-theme
